export default {
  items: [
    {
      name: "Assignment",
      icon: "icon-docs",
      roles: [
        "BAM-PD",
        "BAM-Customer Project Manager",
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-ASP Management",
        "BAM-ASP",
        "BAM-Project Controller",
        "BAM-Project Planner",
      ],
      children: [
        {
          name: "Assignment List",
          url: "/assignment-list",
          icon: "icon-list",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Project Controller",
            "BAM-Project Planner",
          ],
        },
        // {
        //   name: "Assignment NA List",
        //   url: "/assignment-list-approval",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Coordinator",
        //     "BAM-TPM",
        //     "BAM-Customer Project Manager",
        //   ],
        // },
        // {
        //   name: "Assignment List (ASP)",
        //   url: "/assignment-list-asp",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-PD",
        //     "BAM-Customer Project Manager",
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //     "BAM-ASP Management",
        //     "BAM-ASP",
        //   ],
        // },
        // {
        //   name: "Assignment Bulk Notify",
        //   url: "/bulk-assignment-notify",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //   ],
        // },
        // {
        //   name: "Assignment Report",
        //   url: "/assignment-list-report",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-PD",
        //     "BAM-Customer Project Manager",
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //     "BAM-ASP Management",
        //     "BAM-ASP",
        //     "BAM-Project Controller",
        //     "BAM-Project Planner",
        //   ],
        // },
        // {
        //   name: "PRT",
        //   url: "/prt-list",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //   ],
        // },
      ],
    },
    // {
    //    name: 'Plant Spec List',
    //    url: '/ps-list',
    //    icon: 'icon-menu',
    //    roles : ["BAM-Engineering", "BAM-Project Controller", "BAM-Project Planner"],
    //  },
    {
      name: "Material Request",
      icon: "fas fa-tools",
      roles: [
        "BAM-Warehouse",
        "BAM-PD",
        "BAM-Customer Project Manager",
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-Engineering",
        "BAM-LDM",
        "BAM-ASP",
        "BAM-ASPWarehouse",
        "BAM-Mover",
        "BAM-Project Controller",
        "BAM-Project Planner",
      ],
      children: [
        {
          name: "MR Dashboard",
          url: "/mr-dashboard-global",
          icon: "icon-speedometer",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Engineering",
            "BAM-LDM",
            "BAM-ASP",
            "BAM-ASPWarehouse",
            "BAM-Mover",
            "BAM-Project Controller",
            "BAM-Project Planner",
          ],
        },
        {
          name: "MR List",
          url: "/mr-list",
          icon: "icon-list",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Engineering",
            "BAM-LDM",
            "BAM-ASP",
            "BAM-ASPWarehouse",
            "BAM-Mover",
            "BAM-Project Controller",
            "BAM-Project Planner",
          ],
        },
        // {
        //   name: "MR PS Not Assigned",
        //   url: "/mr-na-list",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //     "BAM-Engineering",
        //   ],
        // },
        // {
        //   name: "Bulk MR Request",
        //   url: "/bulk-mr-request",
        //   icon: "icon-plus",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //   ],
        // },
        {
          name: "MRA List",
          url: "/mra-list",
          icon: "icon-list",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
        {
          name: "MRA Need Confirm",
          url: "/mra-list-need-confirm",
          icon: "icon-list",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
      ],
    },
    {
      name: "MR Return/Dismantle",
      icon: "fas fa-tools",
      roles: [
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-Warehouse",
      ],
      children: [
        // {
        //   name: "PS SRN",
        //   url: "/srn/ps-srn-list",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //     "BAM-Warehouse",
        //   ],
        // },
        {
          name: "MRA List",
          url: "/srn/mr-srn-list",
          icon: "icon-list",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
        // {
        //   name: "MRA Assign PS SRN",
        //   url: "/srn/mr-srn-na-list",
        //   icon: "icon-list",
        //   roles: [
        //     "BAM-Implementation Manager",
        //     "BAM-Implementation Coordinator",
        //     "BAM-Warehouse",
        //   ],
        // },
        {
          name: "MRA Approval LDM",
          url: "/srn/mr-srn-need-approval-ldm-list",
          icon: "icon-list",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
        {
          name: "MRA Warehouse Confirm",
          url: "/srn/mr-srn-need-confirm-list",
          icon: "icon-list",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
      ],
    },
    // {
    //   name: "MR Warehouse",
    //   icon: "fas fa-tools",
    //   roles: [
    //     "BAM-Implementation Manager",
    //     "BAM-Implementation Coordinator",
    //     "BAM-Warehouse",
    //   ],
    //   children: [
    //     {
    //       name: "PS Warehouse List",
    //       url: "/toWH/ps-wh-list",
    //       icon: "icon-list",
    //       roles: [
    //         "BAM-Implementation Manager",
    //         "BAM-Implementation Coordinator",
    //         "BAM-Warehouse",
    //       ],
    //     },
    //     {
    //       name: "MR Warehouse",
    //       url: "/toWH/mr-wh-list",
    //       icon: "icon-list",
    //       roles: [
    //         "BAM-Implementation Manager",
    //         "BAM-Implementation Coordinator",
    //         "BAM-Warehouse",
    //       ],
    //     },
    //     {
    //       name: "MR WH Assign PS",
    //       url: "/toWH/mr-wh-na-list",
    //       icon: "icon-list",
    //       roles: [
    //         "BAM-Implementation Manager",
    //         "BAM-Implementation Coordinator",
    //         "BAM-Warehouse",
    //       ],
    //     },
    //     {
    //       name: "MR WH Dispatch",
    //       url: "/toWH/mr-wh-dispatch",
    //       icon: "icon-list",
    //       roles: [
    //         "BAM-Implementation Manager",
    //         "BAM-Implementation Coordinator",
    //         "BAM-Warehouse",
    //       ],
    //     },
    //     {
    //       name: "MR WH Confirm WH",
    //       url: "/toWH/mr-wh-confirm-wh",
    //       icon: "icon-list",
    //       roles: [
    //         "BAM-Implementation Manager",
    //         "BAM-Implementation Coordinator",
    //         "BAM-Warehouse",
    //       ],
    //     },
    //   ],
    // },
    {
      name: "Warehouse",
      icon: "fas fa-boxes",
      roles: [
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-Warehouse",
      ],
      children: [
        {
          name: "Dashboard EID",
          url: "/wh-dashboard-eid",
          icon: "icon-speedometer",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-Warehouse",
          ],
        },
        {
          name: "Dashboard ASP/DSP",
          url: "/wh-dashboard-ext",
          icon: "icon-speedometer",
          roles: [
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
          ],
        },
        {
          name: "Warehouse Management",
          url: "/wh-management",
          icon: "fas fa-pallet",
        },
      ],
    },
    {
      title: true,
      name: "MR Process",
      roles: [
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-Warehouse",
      ],
      wrapper: {
        // optional wrapper object
        element: "", // required valid HTML5 element tag
        attributes: {}, // optional valid JS object with JS API naming ex: { className: "my-class", style: { fontFamily: "Verdana" }, id: "my-id"}
      },
      class: "", // optional class names space delimited list for title item ex: "text-center"
    },
    {
      name: "Order Created",
      url: "/order-created",
      icon: "icon-envelope-open",
      roles: ["BAM-LDM"],
    },
    {
      name: "MR Milestones",
      icon: "icon-paper-plane",
      roles: [
        "BAM-PD",
        "BAM-Customer Project Manager",
        "BAM-Implementation Manager",
        "BAM-Implementation Coordinator",
        "BAM-LDM",
        "BAM-ASP",
        "BAM-ASPWarehouse",
        "BAM-Mover",
        "BAM-Project Controller",
        "BAM-Project Planner",
      ],
      children: [
        {
          name: "Order Received",
          url: "/order-received",
          icon: "fa fa-warehouse",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "Order Processing",
          url: "/order-processing",
          icon: "fa fa-clipboard-list",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "LOM List",
          url: "/lom-list",
          icon: "fa fa-stop-circle",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "Ready to Deliver",
          url: "/ready-to-deliver",
          icon: "fa fa-arrow-right",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "Joint Check",
          url: "/joint-check",
          icon: "fa fa-box-open",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "Loading Process",
          url: "/loading-process",
          icon: "fa fa-truck-loading",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
        {
          name: "Waiting Dispatch",
          url: "/waiting-dispatch",
          icon: "fa fa-truck-moving",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
            "BAM-ASP",
            "BAM-ASPWarehouse",
            "BAM-Mover",
          ],
        },
        {
          name: "Material Dispatch",
          url: "/material-dispatch",
          icon: "fa fa-truck-moving",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
            "BAM-ASP",
            "BAM-ASPWarehouse",
            "BAM-Mover",
          ],
        },
        {
          name: "Shipment",
          url: "/shipment-list",
          icon: "fa fa-truck-moving",
          roles: [
            "BAM-PD",
            "BAM-Customer Project Manager",
            "BAM-Implementation Manager",
            "BAM-Implementation Coordinator",
            "BAM-LDM",
          ],
        },
      ],
    },
  ],
};
